name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
      my_rust_protos_version:
        required: true

jobs:
  pack:
    runs-on: macos-latest
    env:
      RUST_RUNTIMES: "aarch64-darwin aarch64-linux-gnu aarch64-windows x86_64-darwin x86_64-linux-gnu x86_64-windows x86_64-windows-gnu"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: v${{ inputs.version }}
      - name: Setup Java 24 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
          cache: gradle
      - name: cache konan
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
      - name: download binaries
        run: |
          read -a rust_runtimes <<< "${{ env.RUST_RUNTIMES }}"
          for runtime in "${rust_runtimes[@]}"
          do
              mkdir -p ./natives/${runtime}
              curl -L "https://github.com/IgnaciodelaTorreArias/my_rust_protos/releases/download/v${{ inputs.my_rust_protos_version }}/${runtime}.tar.gz" |
              tar -xzf - -C ./natives/${runtime}
          done
          mkdir -p src/jvmMain/resources/jne/macos/aarch64 && cp ./natives/aarch64-darwin/libmy_rust_protos.dylib src/jvmMain/resources/jne/macos/aarch64
          mkdir -p src/jvmMain/resources/jne/linux/aarch64 && cp ./natives/aarch64-linux-gnu/libmy_rust_protos.so src/jvmMain/resources/jne/linux/aarch64
          mkdir -p src/jvmMain/resources/jne/windows/aarch64 && cp ./natives/aarch64-windows/my_rust_protos.dll src/jvmMain/resources/jne/windows/aarch64
          mkdir -p src/jvmMain/resources/jne/macos/x86_64 && cp ./natives/x86_64-darwin/libmy_rust_protos.dylib src/jvmMain/resources/jne/macos/x86_64
          mkdir -p src/jvmMain/resources/jne/linux/x86_64 && cp ./natives/x86_64-linux-gnu/libmy_rust_protos.so src/jvmMain/resources/jne/linux/x86_64
          mkdir -p src/jvmMain/resources/jne/windows/x86_64 && cp ./natives/x86_64-windows/my_rust_protos.dll src/jvmMain/resources/jne/windows/x86_64
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew publishToMavenCentral
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
